services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow-init:   # Initializes Airflow metadata DB
    image: apache/airflow:3.0.6
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"  
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"  
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./wait-for-db.sh:/wait-for-db.sh
    entrypoint: ["/wait-for-db.sh"]
    command: ["airflow", "db", "migrate"]

  airflow-webserver:
    image: apache/airflow:3.0.6
    depends_on:
      - airflow-init
      - postgres
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__API__WORKERS: "4"
    ports:
      - "0.0.0.0:8080:8080"  # Bind to all interfaces for Windows
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./wait-for-db.sh:/wait-for-db.sh
    entrypoint: ["/wait-for-db.sh"]
    command: ["airflow", "api-server"]

  airflow-scheduler:
    image: apache/airflow:3.0.6
    depends_on:
      - airflow-init
      - postgres
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./wait-for-db.sh:/wait-for-db.sh
    entrypoint: ["/wait-for-db.sh"]
    command: ["airflow", "scheduler"]